// import React from "react";
// import Link from "next/link";
// const Home = () => {
//   return (
//     <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
//       <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
//       {/* <p style={{ fontSize: "18px", marginBottom: "30px" }}>
//         This project was generated by{" "}
//         <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
//           Dhiwise
//         </a>
//         <br />
//         . Quickly use below links to navigate through all pages.
//       </p> */}
//       <ul style={{ listStyle: "none", padding: "0" }}>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/landing" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Landing
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/pricingplans" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             PricingPlans
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/homefilelisting" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             HomeFileListing
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/filelistinglistview" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             FileListingListView
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/filelistinggridview" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             FileListingGridView
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/uploadnewfiles" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             UploadNewFiles
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/filedetailsimage" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             FileDetailsImage
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/filedetailsdocument" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             FileDetailsDocument
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/createnewfile" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             CreateNewFile
//           </Link>
//         </li>
//         <li style={{ marginBottom: "10px" }}>
//           <Link href="/fileusagedashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             FileUsageDashboard
//           </Link>
//         </li>
//         {/* <li style={{ marginBottom: "10px" }}>
//           <Link href="/createafolder" style={{ color: "#87CEFA", textDecoration: "none" }}>
//             Create a folder
//           </Link>
//         </li> */}
//       </ul>
//     </div>
//   );
// };
// export default Home;



import React from "react";
import LandingPage from "../app/landing";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "File Sharing Platform",
  description: "A simple web app created for sharing and storing files"
};

const Home = () => {
  return <LandingPage />;
};

export default Home;